# Generated by Django 4.2.4 on 2023-08-07 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_sub_product_category1_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_product_category2',
            old_name='product_category',
            new_name='sub_product_category1',
        ),
    ]
